# Generated by Django 3.0.3 on 2020-11-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videochallenge',
            old_name='description',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='videochallenge',
            name='image',
            field=models.FileField(upload_to='challenge_image', verbose_name='Challenge Image'),
        ),
    ]
