# Generated by Django 3.0.3 on 2020-10-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='imageChallenge',
            field=models.FileField(blank=True, null=True, upload_to='challenge', verbose_name='Challenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='challenge_video', verbose_name='Challenge Video'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='description',
            field=models.CharField(blank=True, default='None description.', max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='challenge_image', verbose_name='Challenge Image'),
        ),
    ]
