# Generated by Django 3.0.3 on 2020-10-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_challenge_imagechallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewhistory',
            name='video',
        ),
        migrations.DeleteModel(
            name='HistoricalUserDetail',
        ),
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
