# Generated by Django 3.0.3 on 2020-10-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_inplaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='InChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Challenge')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Comment')),
            ],
        ),
    ]
