# Generated by Django 3.0.3 on 2020-10-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_inchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistvideo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Playlist Image'),
        ),
    ]
